# -*- coding: utf-8 -*-
"""run_embeddings_hybrid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zeYUHlZ9h5IAFDGqEjuT0ycD4qCRxIFy
"""

from neo4j import GraphDatabase
from sentence_transformers import SentenceTransformer
import numpy as np


import os

def load_config(filename='config.txt'):

    possible_paths = [
        filename,
        os.path.join('..', 'Milestone_02', filename),
        os.path.join('..', filename)
    ]

    config = {}
    found_path = None

    for path in possible_paths:
        if os.path.exists(path):
            found_path = path
            print(f"Found config file at: {found_path}")
            break


    if not found_path:
        print("Warning: config.txt not found. Using default connection settings.")
        return {'URI': "bolt://localhost:7687", 'USERNAME': "neo4j", 'PASSWORD': "password"}


    try:
        with open(found_path, 'r') as file:
            for line in file:
                if '=' in line:
                    key, value = line.strip().split('=', 1)
                    config[key] = value.strip()
        return config
    except Exception as e:
        print(f"Error reading config: {e}")
        return {'URI': "bolt://localhost:7687", 'USERNAME': "neo4j", 'PASSWORD': "password"}





class InputProcessor:
    def __init__(self, model_name):
        print(f"Loading Embedding Model: {model_name}...")
        self.model = SentenceTransformer(model_name)
        self.model_name = model_name

    def embed_input(self, user_text):
        """
        Requirement 1.c: Input Embedding
        Converts user text into a vector representation.
        Returns: List[float]
        """

        vector = self.model.encode(user_text, normalize_embeddings=True)
        return vector.tolist()


class JourneyRetriever:
    def __init__(self, uri, user, password, model_name):
        self.driver = GraphDatabase.driver(uri, auth=(user, password))
        self.processor = InputProcessor(model_name)

    def close(self):
        self.driver.close()

    def prepare_data(self):
        """
        Runs the Cypher query to create the text sentences for all journeys.
        """
        print("Preparing text data in Neo4j...")
        setup_query = """
        MATCH (p:Passenger)-[:TOOK]->(j:Journey)-[:ON]->(f:Flight)
        MATCH (f)-[:DEPARTS_FROM]->(origin:Airport)
        MATCH (f)-[:ARRIVES_AT]->(dest:Airport)
        SET j.text_representation =
            "Flight Number: " + toString(f.flight_number) + ". " +
            "Route: " + origin.station_code + " to " + dest.station_code + ". " +
            "Aircraft: " + f.fleet_type_description + ". " +
            "Distance: " + toString(j.actual_flown_miles) + " miles with " + toString(j.number_of_legs) + " legs. " +
            "Passenger: " + p.generation + " generation, " + p.loyalty_program_level + " member. " +
            "Class: " + j.passenger_class + ". " +
            "Feedback: Food rating " + toString(j.food_satisfaction_score) + "/5. " +
            "Arrival delay: " + toString(j.arrival_delay_minutes) + " minutes."
        """
        with self.driver.session() as session:
            session.run(setup_query)
            print("Text representation updated for all nodes.")

    def generate_and_store_embeddings(self):
        """
        Generates vectors for all Journey nodes and stores them in Neo4j.
        This uses the InputProcessor's model to ensure consistency.
        """
        print("Fetching Journeys from Neo4j...")


        fetch_query = """
        MATCH (j:Journey)
        WHERE j.text_representation IS NOT NULL
        RETURN elementId(j) AS id, j.text_representation AS text
        """


        update_query = """
        MATCH (j:Journey)
        WHERE elementId(j) = $id
        SET j.embedding = $vector
        """

        with self.driver.session() as session:
            results = session.run(fetch_query).data()
            print(f"Found {len(results)} journeys to embed.")

            batch_size = 200
            for i in range(0, len(results), batch_size):
                batch = results[i:i+batch_size]
                texts = [r['text'] for r in batch]
                ids = [r['id'] for r in batch]

                vectors = self.processor.model.encode(texts, normalize_embeddings=True)

                for k, vector in enumerate(vectors):
                    session.run(update_query, id=ids[k], vector=vector.tolist())

                print(f"Processed {i + len(batch)}/{len(results)}...")

    def recreate_index(self):
        """
        Ensures the Vector Index exists with the correct dimensions (384 for BGE-Small).
        """
        drop_query = "DROP INDEX journey_embeddings IF EXISTS"
        index_query = """
        CREATE VECTOR INDEX journey_embeddings IF NOT EXISTS
        FOR (j:Journey)
        ON (j.embedding)
        OPTIONS {indexConfig: {
         `vector.dimensions`: 384,
         `vector.similarity_function`: 'cosine'
        }}
        """
        with self.driver.session() as session:
            session.run(drop_query)
            session.run(index_query)
            print("Vector Index 'journey_embeddings' (re)created.")

    def retrieve_by_vector(self, query_vector, top_k=3):
        """
        Requirement 2.b: Embedding-based Retrieval
        Performs the vector search using a pre-calculated vector.
        """
        search_query = """
        CALL db.index.vector.queryNodes('journey_embeddings', $k, $query_vector)
        YIELD node, score
        RETURN node.text_representation AS text, score
        """

        with self.driver.session() as session:
            results = session.run(search_query, k=top_k, query_vector=query_vector)
            return [record.data() for record in results]


if __name__ == "__main__":
    cfg = load_config()

    print("="*50)
    print("Select Experiment Model:")
    print("1. Experiment 1: all-MiniLM-L6-v2 (Standard)")
    print("2. Experiment 2: BAAI/bge-small-en-v1.5 (Retriever-Optimized)")

    model_choice = input("Enter 1 or 2: ").strip()

    if model_choice == '2':
        SELECTED_MODEL = 'BAAI/bge-small-en-v1.5'
        print(f"\n>> Selected Model: {SELECTED_MODEL} (Experiment 2)")
    else:
        SELECTED_MODEL = 'all-MiniLM-L6-v2'
        print(f"\n>> Selected Model: {SELECTED_MODEL} (Experiment 1)")

    retriever = JourneyRetriever(cfg['URI'], cfg['USERNAME'], cfg['PASSWORD'], SELECTED_MODEL)


    print("\n" + "="*40)
    print("Do you want to RE-GENERATE the embeddings and index? (y/n)")
    choice = input("> ").strip().lower()

    if choice == 'y':
        print("\n[SETUP PHASE] Starting...")
        retriever.prepare_data()
        retriever.generate_and_store_embeddings()
        retriever.recreate_index() # or create_index() depending on your file
        print("[SETUP PHASE] Complete!\n")
    else:
        print("\n[SETUP PHASE] Skipped. Using existing data.\n")
    test_queries = [
        "Flights from LAX with terrible food experience",
        "First class flight with no delays",
        "A smooth flight with excellent food",
        "A horrible journey with long delays",
        "What do Boomers complain about regarding food?",
        "Elite members flying into LAX with bad experiences",
        "Comfortable journey on a Boeing 787",
        "Reviews for Flight 2411"
    ]

    print("\n--- STARTING RETRIEVAL PIPELINE ---\n")

    for query_text in test_queries:
        print(f"User Query: '{query_text}'")

        vector = retriever.processor.embed_input(query_text)
        results = retriever.retrieve_by_vector(vector)

        for r in results:
            print(f"Score: {r['score']:.4f} | {r['text']}")
        print("-" * 50)

    retriever.close()