# -*- coding: utf-8 -*-
"""Validate Satisfaction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXov8svle9IAAm9PzVXtoF-nw6WI_9eM
"""

import math
from neo4j import GraphDatabase

def load_config(file_path='config.txt'):
    config = {}
    try:
        with open(file_path, 'r') as file:
            for line in file:
                if '=' in line:
                    key, value = line.strip().split('=', 1)
                    config[key] = value
        return config
    except FileNotFoundError:
        print(f"Error: {file_path} not found.")
        return None

# Standard Query (The one giving 1925)
QUERY_STANDARD = """
MATCH (p:Passenger)-[:TOOK]->(j:Journey)
WITH p, j,
     toFloat(coalesce(j.food_satisfaction_score, 0)) AS food,
     toFloat(coalesce(j.arrival_delay_minutes, 0)) AS delay_raw,
     toFloat(coalesce(j.number_of_legs, 0)) AS legs_raw,
     toFloat(coalesce(j.actual_flown_miles, 0)) AS miles_raw

WITH p, j, food,
     round(abs(delay_raw) / 20.0, 1) AS delay_calc,
     round(legs_raw * 1.5, 1) AS legs_calc,
     round(miles_raw / 3000.0, 1) AS miles_calc

WITH p, j, food, delay_calc, legs_calc, miles_calc,
     (delay_calc + abs(delay_calc)) / 2.0 AS d_low,
     (legs_calc + abs(legs_calc)) / 2.0 AS l_low,
     (miles_calc + abs(miles_calc)) / 2.0 AS m_low

WITH p, j, food,
     (d_low + 5.0 - abs(d_low - 5.0)) / 2.0 AS delay_clamped,
     (l_low + 5.0 - abs(l_low - 5.0)) / 2.0 AS legs_clamped,
     (m_low + 5.0 - abs(m_low - 5.0)) / 2.0 AS miles_clamped

WITH p, (0.5 * food) + (0.35 * (5.0 - delay_clamped)) + (0.1 * (5.0 - legs_clamped)) + (0.05 * (5.0 - miles_clamped)) AS overall_satisfaction_score
WHERE overall_satisfaction_score > 3
RETURN count(DISTINCT p) as Satisfied_Passengers
"""

# Filtered Query (Excludes Impossible 0-mile/0-leg flights)
QUERY_FILTERED = """
MATCH (p:Passenger)-[:TOOK]->(j:Journey)
// --- DIAGNOSTIC FILTER ---
WHERE j.actual_flown_miles > 0 AND j.number_of_legs > 0
// -------------------------
WITH p, j,
     toFloat(coalesce(j.food_satisfaction_score, 0)) AS food,
     toFloat(coalesce(j.arrival_delay_minutes, 0)) AS delay_raw,
     toFloat(coalesce(j.number_of_legs, 0)) AS legs_raw,
     toFloat(coalesce(j.actual_flown_miles, 0)) AS miles_raw

WITH p, j, food,
     round(abs(delay_raw) / 20.0, 1) AS delay_calc,
     round(legs_raw * 1.5, 1) AS legs_calc,
     round(miles_raw / 3000.0, 1) AS miles_calc

WITH p, j, food, delay_calc, legs_calc, miles_calc,
     (delay_calc + abs(delay_calc)) / 2.0 AS d_low,
     (legs_calc + abs(legs_calc)) / 2.0 AS l_low,
     (miles_calc + abs(miles_calc)) / 2.0 AS m_low

WITH p, j, food,
     (d_low + 5.0 - abs(d_low - 5.0)) / 2.0 AS delay_clamped,
     (l_low + 5.0 - abs(l_low - 5.0)) / 2.0 AS legs_clamped,
     (m_low + 5.0 - abs(m_low - 5.0)) / 2.0 AS miles_clamped

WITH p, (0.5 * food) + (0.35 * (5.0 - delay_clamped)) + (0.1 * (5.0 - legs_clamped)) + (0.05 * (5.0 - miles_clamped)) AS overall_satisfaction_score
WHERE overall_satisfaction_score > 3
RETURN count(DISTINCT p) as Satisfied_Passengers
"""

def run_validation():
    print("Loading configuration...")
    config = load_config()
    if not config: return

    driver = GraphDatabase.driver(config['URI'], auth=(config['USERNAME'], config['PASSWORD']))

    with driver.session() as session:
        print("\n--- DIAGNOSTIC RUN ---")

        # 1. Run Standard
        res1 = session.run(QUERY_STANDARD).single()["Satisfied_Passengers"]
        print(f"Standard Count (Current): {res1}")

        # 2. Run Filtered
        res2 = session.run(QUERY_FILTERED).single()["Satisfied_Passengers"]
        print(f"Filtered Count (>0 miles): {res2}")

        print("\n--- CONCLUSION ---")
        if res2 == 1856:
            print("SUCCESS! The filtered query returned 1856.")
            print("ISSUE: Your database contains journeys with 0 miles or 0 legs.")
            print("FIX: Update create_kg.py to filter: df = df[df['actual_flown_miles'] > 0]")
        elif res1 == 1925:
            print("Still stuck at 1925. The bad data is likely 'Null' treated as 0.")
        else:
            print(f"Got {res2}. We are getting closer.")

    driver.close()

if __name__ == "__main__":
    run_validation()